Fixes #55: Check commit comment length
fooelisa/pyiosxr pull request #56
Opened 2017-11-27 14:00 UTC by Ichabond

Raise an InvalidInputError when the commit message is longer than 60 characters, as this breaks IOS-XR.

2017-11-27 14:25 UTC, loverend commented on pyIOSXR/iosxr.py
> +                raise InvalidInputError('comment needs to be shorter than 60 characters', self)
It can be up to and including 60 characters

2017-11-27 15:23 UTC, Ichabond commented
Thanks to @loverend for the reworded message.

2018-01-12 15:54 UTC, mirceaulinic requested changes

2018-01-12 15:54 UTC, mirceaulinic commented on pyIOSXR/iosxr.py
> +                raise InvalidInputError('comment should be no more than 60 characters', self)
We should just trim the commit message when it's longer than 60 characters.

2018-04-16 11:45 UTC, mirceaulinic approved these changes

2018-04-16 11:45 UTC, merged